name: Cypress tests

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  cypress-run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with: 
        spec: cypress/e2e/production-basic.cy.js
        
    - uses: actions/upload-artifact@v2
        
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-videos
        path: cypress/videos
        
    - uses: ravsamhq/notify-slack-action@v2
      if: always()
      with:
          status: ${{ job.status }} # required
          notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

